### ISSUE TITLE
ExecJS runtime error on Windows (8?)

### ISSUE THREAD

**Issue by rotev** [railsgirls/railsgirls.github.com#133]
step 2 "scaffold" 
Opening http://localhost:3000/ideas
produces an ExecJS runtime error.
A solution can be found in the below link (read option 3 - updating runtimes.rb)
http://stackoverflow.com/questions/12520456/execjsruntimeerror-on-windows-trying-to-follow-rubytutorial

And the file that needs to be updated is located here:
C:\RailsInstaller\Ruby1.9.3\lib\ruby\gems\1.9.1\gems\execjs-2.0.2\lib\execjss

**Comment by mpapis** [comment]
During Rails Girls Berlin Beginners workshop we fixed it with installing [node.js](https://nodejs.org/) followed by closing the _command prompt window_ and opening new one, when in doubt try running `node` to ensure node is available (`CTRL+C` two times to exit the node mode)

**Comment by hsbt** [comment]
fixed at https://github.com/railsgirls/railsgirls.github.com/pull/245
