### ISSUE TITLE
Can't start server (Guide 5: Adding Authentication with Devise)

### ISSUE THREAD

**Issue by declanatticus** [railsgirls/railsgirls.github.com#238]
In the step 5: Create your first user, so I tried to start the server to create account. But it couldn't start and show this:

Declan:railsgirls declan$ rails s
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `devise' for User (call 'User.connection' to establish a connection):Class (NoMethodError)
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/app/models/user.rb:4:in `<class:User>'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/app/models/user.rb:1:in `<top (required)>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:261:in `const_get'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `each'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `inject'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:566:in `get'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:597:in `constantize'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise.rb:302:in `get'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise/mapping.rb:80:in `to'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise/mapping.rb:75:in `modules'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise/mapping.rb:92:in `routes'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise/mapping.rb:159:in `default_used_route'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise/mapping.rb:69:in `initialize'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise.rb:336:in `new'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise.rb:336:in `add_mapping'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:224:in `block in devise_for'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `each'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `devise_for'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/config/routes.rb:2:in `block in <top (required)>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/config/routes.rb:1:in `<top (required)>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `call'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/config/environment.rb:5:in `<top (required)>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/config.ru:3:in `block in <main>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/config.ru:in `new'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/config.ru:in `<main>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/server.rb:78:in `start'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/bin/rails:8:in `require'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/bin/rails:8:in `<top (required)>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.4/lib/spring/client/rails.rb:28:in `load'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.4/lib/spring/client/rails.rb:28:in `call'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.4/lib/spring/client/command.rb:7:in `call'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.4/lib/spring/client.rb:26:in `run'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.4/bin/spring:48:in `<top (required)>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.4/lib/spring/binstub.rb:11:in `load'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/declan/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/declan/Documents/Tuts/Ruby/railsgirls/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

======================================================================

HELP! THANKS!

**Comment by alicetragedy** [comment]
hey @declanatticus, it looks like devise was not set up properly. In your rails app, can you find the devise initializer under `config/initializers/devise.rb`? If not, it might be that you forgot to run `rails generate devise:install` (Step 2). Please let me know if this helped!
