### ISSUE TITLE
Serving bootstrap via HTTPS doesn't work

### ISSUE THREAD

**Issue by leifg** [railsgirls/railsgirls.github.com#261]
In the tutorial, the stylesheets for bootstrap are served from the rails girls server. The according section in the layout looks like this:

    <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
    <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">

That means if the website is opened on an https connection the file is served under this url: https://railsgirls.com/assets/bootstrap.css

Unfortunately the used certificate is not accepted by Chrome and Safari (the only browsers I tested) so the file won't be loaded which means: the site will be rendered without the CSS. Changing the URL to `http://...` works perfectly fine. However, as a deployment to Heroku by default opens the app on an HTTPS connection, the end result after a deployment looks awful. Changing the stylesheet URLs to `http://..` does also **NOT** work (Chrome and Safari disallow serving assets on a HTTP connection when the site itself is called via HTTPS):

I am totally willing to create a pull request but I don't know which way the railsgirls team would like to go. There are several possible solutions for this:

  1. Fix the HTTPS certificate
  2. Serve the bootstrap.css from a CDN that also supports HTTPS
  3. Let users copy the CSS from bootstrap to a local stylesheet

let me know what you think.

**Comment by elliotthilaire** [comment]
@leifg is onto something.

I think updating the certificate would be the best way since the CDN URLs are longer and more prone to mistakes. 

Here is a PR in case that makes life easier for everyone in the meantime. https://github.com/railsgirls/railsgirls.github.com/pull/292

**Comment by vesan** [comment]
Thanks @leifg for reporting this & @elliotthilaire for fixing it! 🎉
